name: hemelb-ci
on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  deps_install_prefix: ${{github.workspace}}/deps-install
  # VMs have 2 cores, double as compilation often IO bound
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  basic-checks:
    name: Basic code quality checks

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check copyright statements
        run: python Scripts/checkCopyright.py

      - name: Check C++ include guards
        run: python Scripts/check_once_guards.py

  code_build:
    name: Build the main HemeLB application, code-only
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Ubuntu-provided dependencies
      shell: bash
      run: >-
        sudo
        apt-get install -y
        libopenmpi-dev
        libtinyxml-dev
        libparmetis-dev
        libboost-dev
        libctemplate-dev
        libhdf5-mpi-dev
        libcppunit-dev

    - uses: actions/cache@v2
      id: deps-cache
      with:
        path: ${{env.deps_install_prefix}}
        key: deps-${{ runner.os }}-${{ hashFiles('dependencies') }}

    - name: "Deps: make build dir"
      if: steps.deps-cache.outputs.cache-hit != 'true'
      run: mkdir -p ${{github.workspace}}/deps-build ${{env.deps_install_prefix}}

    - name: Deps configure
      if: steps.deps-cache.outputs.cache-hit != 'true'
      run: >-
        cmake
        -S ${{github.workspace}}/dependencies
        -B ${{github.workspace}}/deps-build
        -DHEMELB_BUILD_RBC:BOOL=ON
        -DHEMELB_DEPENDENCIES_INSTALL_PATH:STRING=${{env.deps_install_prefix}}

    - name: Deps install
      if: steps.deps-cache.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/deps-build
      run: >-
        cmake
        --build .

    - name: Code make build dir
      run: mkdir -p ${{github.workspace}}/build

    - name: Code configure
      run: >-
        cmake
        -S ${{github.workspace}}/Code
        -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -DHEMELB_DEPENDENCIES_INSTALL_PATH:STRING=${{env.deps_install_prefix}}
        -DHEMELB_BUILD_RBC:BOOL=ON
        -DMPIEXEC_MAX_NUMPROCS:STRING=4
        -DHEMELB_STEERING_LIB:STRING=none

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .

    - name: Run main unit tests
      working-directory: ${{github.workspace}}/build
      run: tests/hemelb-tests

    - name: Run RBC tests
      working-directory: ${{github.workspace}}/build
      run: ../.github/workflows/run-rbc-tests.sh
