name: HemeLB tools python packages
on:
  - push
  - pull_request

jobs:
  python-tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version:
          - 2.7
          - 3.7

    defaults:
      run:
        working-directory: py/hemeTools

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}


      - name: install tox
        run: |
          pip install -U pip setuptools wheel
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox
